# Numpy

* Creating Array
* Craete ndarray with diff Methods
* Array Manipulation
* Arithmetic Operations with Array
* Aggregate Functions For Statistics And Mathematics
* Sorting And Copying
* Slicing And indexig

In [1]:
import numpy as np

In [4]:
np.__version__

'1.18.1'

In [60]:
#Ask Help For Mehtod Info
np.info(np.random.rand)

rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random


## Creating Array 
### Array having all values same data type int, float, comlex, string.

In [5]:
#1D array
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [49]:
print(a.shape,'\n',a.dtype,'\n',a.ndim)

(4,) 
 int32 
 1


In [135]:
#2D array with nested values
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b.shape,'\n',b)

(3, 3) 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#3D array with 3 nested values
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c.shape,'\n',c)

(2, 2, 3) 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
c.shape

(2, 2, 3)

In [12]:
x = np.array([1,2,3.], dtype = complex)
x

array([1.+0.j, 2.+0.j, 3.+0.j])

## Matrix

In [21]:
np.mat(b)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Craete ndarray with diff Methods
### arrange, random, ones, zeros

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
#Create array of evenly space values(step value)
#create array of range (10, 50) with step value 5.
x = np.arange(10,51,5)
print(x,'\n')

x = np.arange(12)
print(x)

[10 15 20 25 30 35 40 45 50] 

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [52]:
#Create array of random values
x = np.random.rand(2,1)
print(x, '\n')

x = np.random.randn(2,3)
print(x, '\n')

x = np.random.random((2,3))
print(x)

[[0.11921012]
 [0.52083049]] 

[[ 0.83221075 -0.33848007  1.96423922]
 [ 0.75167389 -0.90428237  0.82239547]] 

[[0.24746289 0.32697922 0.46784549]
 [0.63691353 0.05949429 0.7208685 ]]


In [116]:
#selection random number from range 4, 10 
#in 2d array becouse we given 2d shape(5,5)
arr = np.random.randint(4, 10, (5,5))
arr

array([[9, 4, 8, 7, 5],
       [7, 5, 6, 6, 9],
       [4, 5, 7, 8, 4],
       [5, 8, 6, 4, 6],
       [9, 4, 5, 5, 6]])

In [40]:
#Create array with evenly divided values
x = np.linspace(1,5,6)
print(x,'\n')

#get 9 evenly space valus bet range(0,2)
x = np.linspace(0,2,9)
print(x)

[1.  1.8 2.6 3.4 4.2 5. ] 

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [51]:
#Reshape the array size
x.reshape(3,3)

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

In [48]:
#Create empty array
np.empty((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [57]:
d = {'key1':[1,2,3], 'key2':[4,5,6], 'key3':[7,8,9]}
x = np.asarray(d)
print(x)
type(x)

{'key1': [1, 2, 3], 'key2': [4, 5, 6], 'key3': [7, 8, 9]}


numpy.ndarray

## Array Manipulation

In [138]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
#TRANSPOSE OF MATRIX
print(b.T)

np.transpose(b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [149]:
#RESHAPE DATA
x = np.random.randint(1,10, (3,2))
print(x)

z = x.reshape(2,3)
z

[[7 5]
 [7 5]
 [9 7]]


array([[7, 5, 7],
       [5, 9, 7]])

In [151]:
x.resize((6,1))
x

array([[7],
       [5],
       [7],
       [5],
       [9],
       [7]])

In [153]:
w = x.reshape(6,1)
w

array([[7],
       [5],
       [7],
       [5],
       [9],
       [7]])

In [156]:
#APPEND VALUES IN NEW ARRAY 
np.append(b,x)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 7, 5, 7, 5, 9, 7])

In [159]:
a

array([1, 2, 3, 4])

In [161]:
#INSSERT NEW ITEM IN ARRAY AND CREATE NEW ARRAY
#np.insert(array, position, value)
np.insert(arr = a, obj = 0, values = 5)

array([5, 1, 2, 3, 4])

In [162]:
#DELETE VALUES FROM  GIVEN INDEX OF ARRAY
#here values at index 1,2 are deleted
np.delete(a, [1,2])

array([1, 4])

In [164]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
np.delete(b, [1,2,3])

array([1, 5, 6, 7, 8, 9])

In [175]:
print(b,'\n\n',y)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[ 0.77870306 -1.25729478  1.85510386]
 [ 0.30903208 -0.09123808  0.39347953]
 [ 0.49450416  0.54501513  1.48749891]]


In [176]:
#CONCATINATE ARRAY
k = np.concatenate((b,y))
k

array([[ 1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ],
       [ 7.        ,  8.        ,  9.        ],
       [ 0.77870306, -1.25729478,  1.85510386],
       [ 0.30903208, -0.09123808,  0.39347953],
       [ 0.49450416,  0.54501513,  1.48749891]])

In [180]:
#SPLITE THE ARRAY HORIZONTALLY
np.hsplit(k,3)

[array([[1.        ],
        [4.        ],
        [7.        ],
        [0.77870306],
        [0.30903208],
        [0.49450416]]),
 array([[ 2.        ],
        [ 5.        ],
        [ 8.        ],
        [-1.25729478],
        [-0.09123808],
        [ 0.54501513]]),
 array([[3.        ],
        [6.        ],
        [9.        ],
        [1.85510386],
        [0.39347953],
        [1.48749891]])]

In [181]:
#SPLITE THE ARRAY VERTICALLY
np.vsplit(k,3)

[array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 7.        ,  8.        ,  9.        ],
        [ 0.77870306, -1.25729478,  1.85510386]]),
 array([[ 0.30903208, -0.09123808,  0.39347953],
        [ 0.49450416,  0.54501513,  1.48749891]])]

## Arithmetic Operations with Array

In [66]:
x = np.arange(0,21,2)
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
#Adition
print(x + x,'\n')

np.add(x,x)

[ 0  4  8 12 16 20 24 28 32 36 40] 



array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [72]:
#Substraction
print(x - x,'\n')

np.subtract(x,x)

[0 0 0 0 0 0 0 0 0 0 0] 



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [74]:
#Division
print(x / x,'\n')

np.divide(x,x)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.] 



C:\Users\Ganesh Patil\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\Ganesh Patil\anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
#Multiply
print(x * x,'\n')

np.multiply(x,x)

[  0   4  16  36  64 100 144 196 256 324 400] 



array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324, 400])

In [99]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
#@ for matrix multiplication
b@b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [78]:
#Print Log Values
np.log(x)

C:\Users\Ganesh Patil\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227])

In [82]:
#print Sin Cos value
print("Sin Values : \n",np.sin(x),'\n')

print("Cos Values : \n",np.cos(x),'\n')

Sin Values : 
 [ 0.          0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111
 -0.53657292  0.99060736 -0.28790332 -0.75098725  0.91294525] 

Cos Values : 
 [ 1.         -0.41614684 -0.65364362  0.96017029 -0.14550003 -0.83907153
  0.84385396  0.13673722 -0.95765948  0.66031671  0.40808206] 



## Aggregate Functions
### For Statistics And Mathematics

In [86]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [84]:
#Squre Root
np.sqrt(x)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
       4.47213595])

In [85]:
x.max()

20

In [87]:
x.min()

0

In [89]:
x.mean()

10.0

In [90]:
x.sum()

110

In [91]:
x.cumsum()

array([  0,   2,   6,  12,  20,  30,  42,  56,  72,  90, 110], dtype=int32)

In [93]:
np.median(x)

10.0

In [94]:
#Correlation Coefficient
np.corrcoef(x)

1.0

In [95]:
#Standard Deviation
np.std(x)

6.324555320336759

In [96]:
x < 11

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [132]:
x[x < 11]

array([ 0,  2,  4,  6,  8, 10])

## Sorting And Copying

In [112]:
b = np.random.randn(3,3)
b

array([[ 0.77870306, -1.25729478,  1.85510386],
       [ 0.30903208, -0.09123808,  0.39347953],
       [ 0.49450416,  0.54501513,  1.48749891]])

In [106]:
b.sort()
b

array([[-1.4915813 , -0.27543971,  0.72925531],
       [-0.70486139,  0.78516994,  0.99958856],
       [ 0.62623803,  0.87453324,  1.04491374]])

In [108]:
b.sort(axis = 0)
b

array([[-1.4915813 , -0.27543971,  0.72925531],
       [-0.70486139,  0.78516994,  0.99958856],
       [ 0.62623803,  0.87453324,  1.04491374]])

In [113]:
#Shallow copy af array
#JUST CREATED NEW POINTER TO ARRAY B CHANGES IN B CAN OCCURE IN Y
y = b
y

array([[ 0.77870306, -1.25729478,  1.85510386],
       [ 0.30903208, -0.09123808,  0.39347953],
       [ 0.49450416,  0.54501513,  1.48749891]])

In [114]:
#DEEP COPY
#NEW ARRAY Y IS CREATED WITH B VALUES
y = np.copy(b)
y

array([[ 0.77870306, -1.25729478,  1.85510386],
       [ 0.30903208, -0.09123808,  0.39347953],
       [ 0.49450416,  0.54501513,  1.48749891]])

## Slicing And indexig

In [127]:
#selection random number from range 4, 10 
#in 2d array becouse we given 2d shape(5,5)
np.random.seed(20)
arr = np.random.randint(4, 10, (5,5))
arr

array([[7, 6, 8, 6, 5],
       [8, 7, 6, 4, 4],
       [9, 6, 6, 7, 7],
       [4, 9, 4, 5, 9],
       [9, 6, 6, 9, 7]])

In [125]:
arr[3:, 3:]   #selecting from parameter row, col. row = 3 to e

array([[5, 9],
       [9, 7]])

In [126]:
arr[1:]   #select from 1st row of array drop 0th row

array([[8, 7, 6, 4, 4],
       [9, 6, 6, 7, 7],
       [4, 9, 4, 5, 9],
       [9, 6, 6, 9, 7]])

In [128]:
arr[:,3:] #select all rows and only last 2 columns

array([[6, 5],
       [4, 4],
       [7, 7],
       [5, 9],
       [9, 7]])

In [129]:
arr[2:4,2:4]

array([[6, 7],
       [4, 5]])

In [131]:
arr[arr>5]

array([7, 6, 8, 6, 8, 7, 6, 9, 6, 6, 7, 7, 9, 9, 9, 6, 6, 9, 7])